name: flowchat
description: "A new chat project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^2.3.0
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  path: ^1.8.3
  uuid: ^3.0.7
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.5
  flutter_local_notifications: ^17.2.2
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/chat_bg.png
    - assets/icon.png

flutter_native_splash:
  color: "#ffffff"   # background color
  image: assets/icon.png   # your app icon for splash
  android: true
  ios: true
